//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Local.Rest.ModelDTO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALERGENOS
    {
        public int ID { get; set; }
        public int ID_INGREDIENTE { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<System.DateTime> MOMENTO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    }
}
