//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Local.Rest.ModelDTO.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeastRestEntities : DbContext
    {
        public TeastRestEntities()
            : base("name=TeastRestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALERGENOS> ALERGENOS { get; set; }
        public virtual DbSet<INGREDIENTES> INGREDIENTES { get; set; }
        public virtual DbSet<PLATOS> PLATOS { get; set; }
        public virtual DbSet<PLATOS_ING> PLATOS_ING { get; set; }
    }
}
